In [1]:
import numpy as np

In [2]:
pecas_vendidas = np.array([150, 120, 90, 210, 300, 250, 180])
display(pecas_vendidas)

array([150, 120,  90, 210, 300, 250, 180])

In [3]:
estimativa_faturamento = np.array(pecas_vendidas * 50)
display(estimativa_faturamento)

array([ 7500,  6000,  4500, 10500, 15000, 12500,  9000])

**Criar máscara Booleana**

In [4]:
# Criar a máscara booleana para vendas estritamente maiores que 200 peças
mascara_pico = pecas_vendidas > 200
print("Máscara booleana para dias de pico:")
display(mascara_pico)

Máscara booleana para dias de pico:


array([False, False, False,  True,  True,  True, False])

In [5]:
# Filtrar 'pecas_vendidas' usando a máscara para obter apenas os dias de pico
dias_pico_vendas = pecas_vendidas[mascara_pico]
print("Vendas nos dias de pico:")
display(dias_pico_vendas)

Vendas nos dias de pico:


array([210, 300, 250])

**Cração da Matriz 2d**

In [6]:
vendas_loja_a = [200, 220, np.nan, 250]
vendas_loja_b = [150, 180, 160, 190]
vendas_loja_c = [300, 310, 290, 330]

matriz_vendas_2d = np.array([vendas_loja_a, vendas_loja_b, vendas_loja_c])

print("Matriz 2D de Vendas:")
display(matriz_vendas_2d)

Matriz 2D de Vendas:


array([[200., 220.,  nan, 250.],
       [150., 180., 160., 190.],
       [300., 310., 290., 330.]])

**Soma dos dados com axis em linhas.**

In [7]:
print('Soma dos dados por linha:')
display(matriz_vendas_2d.sum(axis=1))

Soma dos dados por linha:


array([  nan,  680., 1230.])

**Média geral ignorando os dados nan**

In [8]:
print('média geral sem nan: ')
display(np.nanmean(matriz_vendas_2d))


média geral sem nan: 


np.float64(234.54545454545453)

**Meta com Where**

In [9]:
meta=np.where(matriz_vendas_2d > 200, 'Meta alcançada', 'Abaixo')
print('Registro de metas: ', meta)

Registro de metas:  [['Abaixo' 'Meta alcançada' 'Abaixo' 'Meta alcançada']
 ['Abaixo' 'Abaixo' 'Abaixo' 'Abaixo']
 ['Meta alcançada' 'Meta alcançada' 'Meta alcançada' 'Meta alcançada']]


### Simulação de Base de Clientes com `np.random.default_rng()`

`np.random.default_rng()` é a função recomendada para criar um novo gerador de números aleatórios no NumPy, oferecendo uma arquitetura mais moderna e robusta em comparação com o gerador legado (`np.random.RandomState`).

Ao passar uma semente (`seed`) para `default_rng()`, garantimos que a sequência de números aleatórios gerada seja sempre a mesma, o que é crucial para a **reprodutibilidade** de experimentos e análises de dados.

In [12]:
# Definir as categorias de produtos
departamento = ['Eletrônicos', 'Roupas', 'Casa']

# Gerar uma amostra de 50 vendas sorteadas entre as categorias
amostra_vendas = rng.choice(departamento, size=50)

print("Amostra de 50 vendas simuladas:")
display(amostra_vendas)

# Opcional: Contar a frequência de cada categoria na amostra
print("\nFrequência das categorias na amostra:")
import pandas as pd
display(pd.Series(amostra_vendas).value_counts())

Amostra de 50 vendas simuladas:


array(['Eletrônicos', 'Casa', 'Casa', 'Casa', 'Casa', 'Roupas', 'Casa',
       'Roupas', 'Eletrônicos', 'Casa', 'Roupas', 'Eletrônicos', 'Roupas',
       'Casa', 'Eletrônicos', 'Roupas', 'Eletrônicos', 'Casa', 'Roupas',
       'Eletrônicos', 'Eletrônicos', 'Roupas', 'Casa', 'Casa', 'Roupas',
       'Eletrônicos', 'Casa', 'Roupas', 'Casa', 'Eletrônicos',
       'Eletrônicos', 'Casa', 'Casa', 'Roupas', 'Casa', 'Casa', 'Roupas',
       'Casa', 'Eletrônicos', 'Eletrônicos', 'Casa', 'Roupas',
       'Eletrônicos', 'Casa', 'Eletrônicos', 'Casa', 'Eletrônicos',
       'Casa', 'Casa', 'Casa'], dtype='<U11')


Frequência das categorias na amostra:


,count
Casa,23
Eletrônicos,15
Roupas,12


**Valores unicos**

In [15]:
unicos, contagens = np.unique(amostra_vendas, return_counts=True)
print("Valores únicos:", unicos)
print("Contagens:", contagens)

Valores únicos: ['Casa' 'Eletrônicos' 'Roupas']
Contagens: [23 15 12]


**Indice maior valor array**

In [16]:
faturamento = np.array([12000, 45000, 23000, 89000, 31000])
print('maior faturamento: ', faturamento.argmax())

maior faturamento:  3


**Sequências e tipagens de dados**

In [17]:
dias_do_mes = np.arange(1, 31)

print("Array dos dias do mês:")
display(dias_do_mes)

Array dos dias do mês:


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

**Array de Metas**

In [18]:
novas_metas=np.linspace(20000,30000,5)
print('Metas: ', novas_metas)

Metas:  [20000. 22500. 25000. 27500. 30000.]


**Conversão de decimal para inteiro**

In [19]:
estoque_fisico_decimal = np.array([10.5,20.1,30.9])
estoque_fisico_inteiro = estoque_fisico_decimal.astype(int)
print('Estoque físico corrigido: ', estoque_fisico_inteiro)

Estoque físico corrigido:  [10 20 30]


**Fatiamento com passo negativo**

In [20]:
ultimos_5_dias_invertidos = dias_do_mes[-5:][::-1]
print('Os últimos 5 dias do mês em ordem invertida são:')
display(ultimos_5_dias_invertidos)

Os últimos 5 dias do mês em ordem invertida são:


array([30, 29, 28, 27, 26])

**Reorganizando dados com `reshape()`**

In [21]:
# Criar um array unidimensional com 12 elementos (representando visitas mensais)
visitas_mensais = np.array([10000, 11000, 12000, 10500, 11500, 12500, 13000, 12000, 11000, 10000, 9500, 9000])

print("Array unidimensional de visitas mensais:")
display(visitas_mensais)

Array unidimensional de visitas mensais:


array([10000, 11000, 12000, 10500, 11500, 12500, 13000, 12000, 11000,
       10000,  9500,  9000])

In [22]:
# Reorganizar o array em uma matriz 4x3 (4 trimestres com 3 meses cada)
matriz_trimestral_visitas = visitas_mensais.reshape(4, 3)

print("Matriz trimestral de visitas (4 trimestres, 3 meses/trimestre):")
display(matriz_trimestral_visitas)

Matriz trimestral de visitas (4 trimestres, 3 meses/trimestre):


array([[10000, 11000, 12000],
       [10500, 11500, 12500],
       [13000, 12000, 11000],
       [10000,  9500,  9000]])

**Combinando Matrizes com `np.vstack()`**

In [23]:
# Dados de visitas para o primeiro semestre (exemplo: 2 trimestres x 3 meses cada)
visitas_primeiro_semestre = np.array([
    [10000, 11000, 12000],  # 1º Trimestre
    [10500, 11500, 12500]   # 2º Trimestre
])

print("Dados de visitas do Primeiro Semestre:")
display(visitas_primeiro_semestre)

# Dados de visitas para o segundo semestre (exemplo: 2 trimestres x 3 meses cada)
visitas_segundo_semestre = np.array([
    [13000, 12000, 11000],  # 3º Trimestre
    [10000, 9500, 9000]    # 4º Trimestre
])

print("\nDados de visitas do Segundo Semestre:")
display(visitas_segundo_semestre)

Dados de visitas do Primeiro Semestre:


array([[10000, 11000, 12000],
       [10500, 11500, 12500]])


Dados de visitas do Segundo Semestre:


array([[13000, 12000, 11000],
       [10000,  9500,  9000]])

In [24]:
# Combinar as duas matrizes verticalmente usando np.vstack()
visitas_anuais_combinadas = np.vstack((visitas_primeiro_semestre, visitas_segundo_semestre))

print("\nMatriz combinada de visitas anuais:")
display(visitas_anuais_combinadas)


Matriz combinada de visitas anuais:


array([[10000, 11000, 12000],
       [10500, 11500, 12500],
       [13000, 12000, 11000],
       [10000,  9500,  9000]])

**Extraindo o Primeiro Trimestre com `copy()` para Projeção**

In [25]:
# Extrair o primeiro trimestre (primeira linha) da matriz combinada e criar uma cópia
primeiro_trimestre_projecao = visitas_anuais_combinadas[0, :].copy()

print("Primeiro Trimestre para Projeção (cópia):")
display(primeiro_trimestre_projecao)

# Exemplo para mostrar que a cópia é independente:
# Alterando um valor na cópia não afeta o array original
primeiro_trimestre_projecao[0] = 99999
print("\nPrimeiro Trimestre de Projeção após alteração:")
display(primeiro_trimestre_projecao)

print("\nVerificando o array original (deve permanecer inalterado):")
display(visitas_anuais_combinadas)

Primeiro Trimestre para Projeção (cópia):


array([10000, 11000, 12000])


Primeiro Trimestre de Projeção após alteração:


array([99999, 11000, 12000])


Verificando o array original (deve permanecer inalterado):


array([[10000, 11000, 12000],
       [10500, 11500, 12500],
       [13000, 12000, 11000],
       [10000,  9500,  9000]])

**Exportando Dados para Relatório com `ravel()`**

In [26]:
# Achatar a matriz de visitas anuais combinadas em um array 1D
relatorio_visitas_1d = visitas_anuais_combinadas.ravel()

print("Array 1D de visitas para relatório:")
display(relatorio_visitas_1d)

Array 1D de visitas para relatório:


array([10000, 11000, 12000, 10500, 11500, 12500, 13000, 12000, 11000,
       10000,  9500,  9000])

**Ranking, Broadcast e Resolução de Sistemas**

In [29]:
pontuacao_alunos = np.array([85,92,78,95,88])
print('ordenação por indices: ', np.argsort(pontuacao_alunos))

ordenação por indices:  [2 0 4 1 3]


In [32]:
precos_base = np.array([10.50, 25.75, 5.25, 15.20, 30.99])
print("Vetor de preços base:")
display(precos_base)

Vetor de preços base:


array([10.5 , 25.75,  5.25, 15.2 , 30.99])

In [33]:
# Transformar o vetor de preços base em um vetor coluna usando np.newaxis
precos_base_coluna = precos_base[:, np.newaxis]

print("Vetor de preços base como coluna:")
display(precos_base_coluna)
print("Forma do vetor de preços base como coluna:", precos_base_coluna.shape)

Vetor de preços base como coluna:


array([[10.5 ],
       [25.75],
       [ 5.25],
       [15.2 ],
       [30.99]])

Forma do vetor de preços base como coluna: (5, 1)


**Equação Linear**

In [34]:
A = np.array([[2, 1], [1, -1]])
b = np.array([500, 100])

solucoes = np.linalg.solve(A, b)

print("O custo da placa robótica é R$", solucoes[0])
print("O custo do sensor é R$", solucoes[1])

O custo da placa robótica é R$ 200.0
O custo do sensor é R$ 100.0
